version: '3.9'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@321
      MYSQL_DATABASE: api
    ports:
      - 3306:3306
    networks:
      - api-network
  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - api-network
    volumes:
      - ./:/app

networks:
  api-network:
    driver: bridge
  